### ISSUE TITLE
Spam TI OMAP PowerHAL error.

### ISSUE THREAD

**Issue by Max1337** [MoKee/android_device_samsung_superior#2]
Every time I touch the screem logcat is spammed with TI OMAP PowerHAL erros and the phone is hot as hell and very fast discharging!
Here's logcat https://drive.google.com/file/d/0B0xt7fDdW0wiT3VDSWx0eVRHdWc/view?usp=sharing

![tqkffimfmaq](https://cloud.githubusercontent.com/assets/13905162/9875432/8e347e64-5be0-11e5-8939-2e48531fedb9.jpg)

**Comment by Ryuinferno** [comment]
You changed governors didn't you? The system is tailored to work with interactive

**Comment by Max1337** [comment]
I tried to put different Governors(Conservative,Powersave,ondemand) but it  nothing helps. I wouldn't write this bugreport if i nothing checked. Please open this issue. Battery Discharging fast regardless CPU max frequency and governors.

**Comment by Ryuinferno** [comment]
We do not accept bug reports here, that's why it's closed. If you set the governor back to interactive, this would probably be solved.
